### ISSUE TITLE
Player frame

### ISSUE THREAD

**Issue by razorshultz** [clicketz/buff-overlay#10]
### Description

Hi, this is a brilliant addon. Is it possible to make it work with Player frames, for when we're solo? I am using SUF and would love to have it consistent with my party frames and raid frames now.

**Comment by clicketz** [comment]
Can you explain the behavior with solo frames? Is it a different frame completely? I'm definitely for adding the compatibility as long as it's similar to raid frames.

**Comment by razorshultz** [comment]
I believe it is, looking at https://github.com/Shadowed/ShadowedUnitFrames

the frames seem to be treated the same and just have their own configurations, and the player solo frame is also customisable within SUF with all the same options and such. I've actually never worked on a WoW addon before, sorry if that's not too helpful.

**Comment by clicketz** [comment]
Oh sorry, I was just asking if the solo frame was a square like raid frames and didn't look more like the player frame.

I'll take a look at SUF and see what I can do :)

**Comment by clicketz** [comment]
Okay, I misunderstood/misread at first. Now I think I understand what you want. You want auras to show on the player frame at all times because in SUF it's similar to how the party frames are, right?

**Comment by razorshultz** [comment]
That's it yep, if i can have BO on the player frame just like the party/raid frames, then SUF+BO is way better than vuhdo I think.

**Comment by clicketz** [comment]
I see. Okay, that's definitely possible. Very addon specific since some addons treat their playerframe very differently in how it looks. I'll see what I can scrap up :)

**Comment by razorshultz** [comment]
Thanks! I used lua for some modding in shadow of chernobyl but never made any WoW addons yet. I'll have to read up on addon development and see if I can help

**Comment by clicketz** [comment]
Sorry about the wait, I've been a little busy. I added this for SUF in the most recent update, let me know how it's working for ya.

**Comment by razorshultz** [comment]
No problem at all! I just tested it having downloaded it from the github page and i can say it works perfectly. SUF + BO is what i'll use for my player/raid/party frames from now on. It combines the positioning and customisation of SUF for frames with BO's much better buff display.

I'll use SUF for debuffs having them just below the frames. But this is going to help amazingly with my healing, and I don't need to spend a year configuring those bulky addons like Vuhdo. This is a game changer for me! Thanks a lot.

**Comment by clicketz** [comment]
Cool, glad it's workin good for you :)

Cheers

**Comment by doxmare** [comment]
This commit made some unwanted changes for people who don't want BuffOverlay to display on player frame with SUF, we cannot disable this, even though Frame Types player is deselected.

**Comment by clicketz** [comment]
Hmm, I just tested and found that un-checking player frame type did indeed remove the overlays from the player frame in SUF. Are you using multiple bars by chance? You'll have to disable player in all the bars.
