### ISSUE TITLE
Masque support

### ISSUE THREAD

**Issue by Unmoist** [clicketz/buff-overlay#11]
### Description

Any chance of Masque support?

**Comment by clicketz** [comment]
Yeah, I'm not against it

**Comment by Unmoist** [comment]
Long wait time for something like that or? 🙂

**Comment by clicketz** [comment]
It's relatively low priority so no ETA, but you can probably expect it in the next release.

**Comment by Unmoist** [comment]
See that's dirty! 
Can't wait. ❤️

**Comment by clicketz** [comment]
Finally got around to this. Feel free to re-open if there's any issues.
