### ISSUE TITLE
Grow direction wrong. 

### ISSUE THREAD

**Issue by Unmoist** [clicketz/buff-overlay#13]
### Description

After update Grow direction is not working. It will not grow Horizontal. 

### BuffOverlay Version

v12.6.6

### World of Warcraft Flavor

Retail

### Sterile Testing

Yes

### Editing Lua Files

No

### Frames Used

Grid2

### Reproduction Steps

Using Grow direction?

**Comment by clicketz** [comment]
Pushed out a fix for this just a few minutes ago, haha

Should be fixed with caa43b5

Let me know if there's still an issue after updating :)

**Comment by clicketz** [comment]
Closing this as fixed. Feel free to reopen if needed.
