### ISSUE TITLE
Lua Error in 10.2

### ISSUE THREAD

**Issue by JyanseiCoding** [clicketz/buff-overlay#15]
### Description

This happens when I disable all abilities and try to reenable them

### BuffOverlay Version

v12.6.16

### World of Warcraft Flavor

Retail

### Sterile Testing

Yes

### Editing Lua Files

Yes

### Frames Used

Default Blizzard Frames

### Lua Error

1x BuffOverlay/Options.lua:1254: attempt to index field 'enabled' (a nil value)

[string "@BuffOverlay/Options.lua"]:1254: in function <BuffOverlay/Options.lua:1246>

[string "=[C]"]: ?

[string "@BuffOverlay/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:45: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:43>

[string "@BuffOverlay/Libs/AceConfig-3.0-3/AceConfigDialog-3.0-86/AceConfigDialog-3.0.lua"]:836: in function <...nfig-3.0/AceConfigDialog-3.0/AceConfigDialog-3.0.lua:658>

[string "=[C]"]: ?

[string "@BuffOverlay/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:66: in function <...ceBuffOverlay/Libs/AceGUI-3.0/AceGUI-3.0.lua:64>

[string "@BuffOverlay/Libs/AceGUI-3.0-41/AceGUI-3.0.lua"]:300: in function `Fire'

[string "@BuffOverlay/Libs/AceGUI-3.0-41/widgets/AceGUIWidget-Button.lua"]:22: in function <...rlay/Libs/AceGUI-3.0/widgets/AceGUIWidget-Button.lua:19>

 

Locals:

dialogIsOpen = nil

(for generator) = <function> defined =[C]:-1

(for state) = <table> {

 196555 = <table> {

 }

 363916 = <table> {

 }

 198111 = <table> {

 }

 25771 = <table> {

 }

 Eating/Drinking = <table> {

 }

 424655 = <table> {

 }

 81256 = <table> {

 }

 145629 = <table> {

 }

 410305 = <table> {

 }

 187827 = <table> {

 }

### Reproduction Steps

Go to Spells
Disable All
Then Enable All
Error Pops Up

**Comment by clicketz** [comment]
Thanks for the bug report! Fixed in latest release.
