### ISSUE TITLE
Lua Error after latest update

### ISSUE THREAD

**Issue by JyanseiCoding** [clicketz/buff-overlay#16]
### Description

I got this Lua Error after the latest update (v12.6.18). I'd removed the old saved variables and did a fresh reinstall, and I was greeted by the lua error below upon login. Bug sack wouldn't stop going off. It did stop giving me the error after a reload though,

I thought it might have been a fluke, so I deleted the saved variables again and reinstalled only to be met with the same error

### BuffOverlay Version

v12.6.18

### World of Warcraft Flavor

Retail

### Sterile Testing

Yes

### Editing Lua Files

No

### Frames Used

Default Blizzard Frames

### Lua Error

5x BuffOverlay/BuffOverlay.lua:1341: attempt to compare number with nil
[string "@BuffOverlay/BuffOverlay.lua"]:1341: in function <BuffOverlay/BuffOverlay.lua:1328>
[string "@BuffOverlay/BuffOverlay.lua"]:1373: in function `ApplyOverlay'
[string "@BuffOverlay/BuffOverlay.lua"]:1615: in function <BuffOverlay/BuffOverlay.lua:1612>
[string "=[C]"]: in function `CompactUnitFrame_UpdateAuras'
[string "@FrameXML/CompactUnitFrame.lua"]:101: in function <FrameXML/CompactUnitFrame.lua:52>

Locals:
bar = <table> {
 neverShow = false
 showCooldownSpiral = true
 iconScale = 1
 showInBattleground = true
 iconCount = 4
 stackCountScale = 0.900000
 id = "Bar1"
 maxGroupSize = 40
 name = "Bar1"
 iconBorder = true
 iconAlpha = 1
 growDirection = "HORIZONTAL"
 showStackCount = true
 cooldownNumberScale = 1
 showCooldownNumbers = false
 showInArena = true
 minGroupSize = 0
 iconBorderColor = <table> {
 }
 debuffIconBorderColorByDispelType = true
 iconAnchor = "BOTTOM"
 iconSpacing = 0
 showTooltip = true
 frameTypes = <table> {
 }
 showInRaid = true
 iconXOff = 0
 showInDungeon = true
 iconYOff = 0
 showInScenario = true
 showInWorld = true
 buffIconBorderColorByDispelType = false
 iconRelativePoint = "CENTER"
 iconBorderSize = 1
}
frameType = "party"
instanceType = nil
numGroupMembers = nil
(*temporary) = 40
(*temporary) = "attempt to compare number with nil"
BuffOverlay = <table> {
 CreatePriorityDialog = <function> defined @BuffOverlay/Options.lua:621
 SetDefaultModuleLibraries = <function> defined @BigDebuffs/Libs/AceAddon-3.0/AceAddon-3.0.lua:363
 UpdateUnits = <function> defined @BuffOverlay/AddonCompatibility.lua:450
 Colorize = <function> defined @BuffOverlay/BuffOverlay.lua:232
 Enable = <function> defined @BigDebuffs/Libs/AceAddon-3.0/AceAddon-3.0.lua:290
 RegisterChatCommand = <function> defined @BuffOverlay/Libs/AceConsole-3.0/AceConsole-3.0.lua:81
 UpdateCustomBuffs = <function> defined @BuffOverlay/BuffOverlay.lua:515
 EnableModule = <function> defined @BigDebuffs/Libs/AceAddon-3.0/AceAddon-3.0.lua:328
 modules = <table> {
 }
 GetModule = <function> defined @BigDebuffs/Libs/AceAddon-3.0/AceAddon-3.0.lua:206
 IterateEmbeds = <function> defined @BigDebuffs/Libs/AceAddon-3.0/AceAddon-3.0.lua:438
 baseName = "BuffOverlay"
 ShowVersion = <function> defined @BuffOverlay/Options.lua:236
 defaultModuleLibraries = <table> {
 }
 AddBarToOptions = <function> defined @BuffOverlay/Options.lua:718
 Options = <function> defined @BuffOverlay/Options.lua:1753
 UnregisterChatCommand = <function> defined @BuffOverlay/Libs/AceConsole-3.0/AceConsole-3.0.lua:107
 defaultSpells = <table> {
 }
 HideGlows = <function> defined @BuffOverlay/BuffOverlay.lua:1252
 FullRefresh = <function> defined @BuffOverlay/BuffOverlay.lua:981
 Printf = <function> defined @BuffOverlay/Libs/AceConsole-3.0/AceConsole-3.0.lua:65
 ApplyOverlay = <function> defined @BuffOverlay/BuffOverlay.lua:1356
 SetDefaultModulePrototype = <function> defined @BigDebuffs/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 AddBar = <function> defined @BuffOverlay/BuffOverlay.lua:256
 InsertCustomAura = <function> defined @BuffOverlay/BuffOverlay.lua:328
 GetIconString = <function> defined @BuffOverlay/Options.lua:240
 name = "BuffOverlay"
 RefreshOverlays = <function> defined @BuffOverlay/BuffOverlay.lua:940
 IsEnabled = <function> defined @BigDebuffs/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 orderedModules = <table> {
 }
 ignoreParentIcons = <table> {
 }
 DisableModule = <function> defined @BigDebuffs/Libs/AceAddon-3.0/AceAddon-3.0.lua:346
 InsertCustomChild = <function> defined @BuffOverlay/BuffOverlay.lua:354
 customIcons = <table> {
 }
 SetupContainer = <function> defined @BuffOverlay/BuffOverlay.lua:1319
 AddToCustom = <function> defined @BuffOverlay/Options.lua:1724
 L = <table> {
 }
 GetArgs = <function> defined @BuffOverlay/Libs/AceConsole-3.0/AceConsole-3.0.lua:140
 frames = <table> {
 }
 GetSingleTestAura = <function> defined @BuffOverlay/BuffOverlay.lua:1033
 OnInitialize = <function> defined @BuffOverlay/BuffOverlay.lua:852
 UpdateBarOptionsTable = <functio

### Reproduction Steps

Delete Addon along with all saved variables
Reinstall Addon
Log in with Addon running
Error

**Comment by clicketz** [comment]
ah yeah, that makes sense. Will push out a fix soon
