### ISSUE TITLE
Protected Function Lua Error

### ISSUE THREAD

**Issue by JyanseiCoding** [clicketz/buff-overlay#17]
### Description

I wish I had more details, but this just popped after I'd teleported out of a raid to Orgrimmar. I pressed an ability on my action bar and my action was blocked. The blocking, and the errors stop after a reload. 

I couldn't really do any sterile testing because this is not an error I could regularly reproduce. It has happened before though in other circumstances. For instance, at the start of an arena match.

### BuffOverlay Version

v12.6.19

### World of Warcraft Flavor

Retail

### Sterile Testing

No

### Editing Lua Files

No

### Frames Used

Default

### Lua Error

[ADDON_ACTION_FORBIDDEN] AddOn 'BuffOverlay' tried to call the protected function 'UseAction()'.
[string "@!BugGrabber/BugGrabber.lua"]:481: in function <!BugGrabber/BugGrabber.lua:481>
[string "=[C]"]: in function `UseAction'
[string "@FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@FrameXML/SecureTemplates.lua"]:690: in function <FrameXML/SecureTemplates.lua:672>
[string "@FrameXML/SecureTemplates.lua"]:704: in function <FrameXML/SecureTemplates.lua:697>
[string "@FrameXML/SecureTemplates.lua"]:746: in function `SecureActionButton_OnClick'
[string "@FrameXML/ActionButton.lua"]:100: in function `TryUseActionButton'
[string "@FrameXML/MultiActionBars.lua"]:23: in function `MultiActionButtonDown'
[string "MULTIACTIONBAR1BUTTON4"]:2: in function <[string "MULTIACTIONBAR1BUTTON4"]:1>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:487
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:487
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:553
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:553
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:547
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:562
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:507
}

### Reproduction Steps

Random error that I can not reproduce on demand

**Comment by clicketz** [comment]
This is likely caused by addon taint that passes blame on to BuffOverlay (most likely not BO, as it has no interaction with actionbars whatsoever). If this happens often enough, you can try turning on taint log via `/console taintLog 2` and post it here and I'd be happy to check it out and see if there's something I can do on my end.

**Comment by clicketz** [comment]
This has been an ongoing problem since dragonflight release for many addons, using an addon such as https://www.curseforge.com/wow/addons/notaint2 might help curb this happening in general.

**Comment by JyanseiCoding** [comment]
I see. I figured it was something on Blizzard's end because this has happened with several other addons in the past, such as WeakAuras. I'll be closing this then, and will install NoTaint2 to see if there are any improvements.

Thank you for the swift response!
