### ISSUE TITLE
Error messages galore.

### ISSUE THREAD

**Issue by tickix** [clicketz/buff-overlay#4]
### Description

Addon doesn't work properly anymore. I get 20+ errors. I pasted a couple of the error messages (there's usually 20+).

### Buff Overlay Version

v11.4.1

### World of Warcraft Flavor

Wrath of the Lich King Classic

### Sterile Testing

Yes

### Editing Lua Files

Yes

### File Edited

added a couple spells to the list.

### Frames Used

default frames.

### Lua Error

Message: Interface\AddOns\BuffOverlay\BuffOverlay.lua:491: attempt to index field 'frames' (a nil value)
Time: Mon Oct  3 04:54:51 2022
Count: 5
Stack: Interface\AddOns\BuffOverlay\BuffOverlay.lua:491: attempt to index field 'frames' (a nil value)
[string "@Interface\AddOns\BuffOverlay\BuffOverlay.lua"]:491: in function <Interface\AddOns\BuffOverlay\BuffOverlay.lua:488>
[string "=[C]"]: ?
[string "=[C]"]: in function `CompactUnitFrame_UpdateAuras'
[string "@Interface_Wrath\FrameXML\CompactUnitFrame.lua"]:308: in function `CompactUnitFrame_UpdateAll'
[string "@Interface_Wrath\FrameXML\CompactUnitFrame.lua"]:177: in function `CompactUnitFrame_SetUnit'
[string "@Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:318: in function `CompactRaidFrameContainer_AddUnitFrame'
[string "@Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:254: in function `CompactRaidFrameContainer_AddPlayers'
[string "@Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:176: in function `CompactRaidFrameContainer_LayoutFrames'
[string "@Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:130: in function `CompactRaidFrameContainer_TryUpdate'
[string "@Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua"]:95: in function `CompactRaidFrameContainer_SetFlowSortFunction'
[string "@Interface_Wrath\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameManager.lua"]:416: in function <...mpactRaidFrames\Blizzard_CompactRaidFrameManager.lua:413>
[string "@Interface_Wrath\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameManager.lua"]:502: in function `CompactRaidFrameManager_SetSetting'
[string "@Interface\AddOns\Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:565: in function `func'
[string "@Interface\AddOns\Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:542: in function `CompactUnitFrameProfiles_ApplyProfile'
[string "@Interface\AddOns\Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:173: in function `CompactUnitFrameProfiles_ApplyCurrentSettings'
[string "@Interface\AddOns\Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:169: in function `CompactUnitFrameProfiles_ActivateRaidProfile'
[string "@Interface\AddOns\Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:42: in function `CompactUnitFrameProfiles_ValidateProfilesLoaded'
[string "@Interface\AddOns\Blizzard_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua"]:28: in function <...rd_CUFProfiles\Blizzard_CompactUnitFrameProfiles.lua:17>

Locals: frame = CompactRaidFrame5 {
 0 = <userdata>
 debuffFrames = <table> {
 }
 maxDispelDebuffs = 3
 inUse = true
 inVehicle = false
 background = CompactRaidFrame5Background {
 }
 powerBar = CompactRaidFrame5PowerBar {
 }
 hasDispelPoison = false
 healthBar = CompactRaidFrame5HealthBar {
 }
 overAbsorbGlow = CompactRaidFrame5OverAbsorbGlow {
 }
 hasDispelDisease = false
 horizTopBorder = CompactRaidFrame5HorizTopBorder {
 }
 vertRightBorder = CompactRaidFrame5VertRightBorder {
 }
 myHealPrediction = CompactRaidFrame5MyHealPrediction {
 }
 aggroHighlight = CompactRaidFrame5AggroHighlight {
 }
 myHealAbsorbRightShadow = CompactRaidFrame5MyHealAbsorbRightShadow {
 }
 overHealAbsorbGlow = CompactRaidFrame5OverHealAbsorbGlow {
 }
 newUnit = true
 hasDispelMagic = false
 hasDispelCurse = false
 selectionHighlight = CompactRaidFrame5SelectionHighlight {
 }
 myHealAbsorbLeftShadow = CompactRaidFrame5MyHealAbsorbLeftShadow {
 }
 totalAbsorbOverlay = CompactRaidFrame5TotalAbsorbOverlay {
 }
 unit = "party4"
 unitExists = true
 displayedUnit = "party4"
 unusedFunc = <function> defined @Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:46
 updateAllEvent = "GROUP_ROSTER_UPDATE"
 statusText = CompactRaidFrame5StatusText {
 }
 horizDivider = CompactRaidFrame5HorizDivider {
 }
 applyFunc = <function> defined @Interface\

-------------------
Message: Interface\AddOns\BuffOverlay\BuffOverlay.lua:491: attempt to index field 'frames' (a nil value)
Time: Mon Oct  3 04:55:26 2022
Count: 16
Stack: Interface\AddOns\BuffOverlay\BuffOverlay.lua:491: attempt to index field 'frames' (a nil value)
[string "@Interface\AddOns\BuffOverlay\BuffOverlay.lua"]:491: in function <Interface\AddOns\BuffOverlay\BuffOverlay.lua:488>
[string "=[C]"]: ?
[string "=[C]"]: in function `CompactUnitFrame_UpdateAuras'
[string "@Interface_Wrath\FrameXML\CompactUnitFrame.lua"]:100: in function <Interface_Wrath\FrameXML\CompactUnitFrame.lua:53>

Locals: frame = CompactRaidFrame5 {
 0 = <userdata>
 debuffFrames = <table> {
 }
 maxDispelDebuffs = 3
 inUse = true
 inVehicle = false
 background = CompactRaidFrame5Background {
 }
 powerBar = CompactRaidFrame5PowerBar {
 }
 hasDispelPoison = false
 healthBar = CompactRaidFrame5HealthBar {
 }
 overAbsorbGlow = CompactRaidFrame5OverAbsorbGlow {
 }
 hasDispelDisease = false
 horizTopBorder = CompactRaidFrame5HorizTopBorder {
 }
 vertRightBorder = CompactRaidFrame5VertRightBorder {
 }
 myHealPrediction = CompactRaidFrame5MyHealPrediction {
 }
 aggroHighlight = CompactRaidFrame5AggroHighlight {
 }
 inDistance = false
 myHealAbsorbRightShadow = CompactRaidFrame5MyHealAbsorbRightShadow {
 }
 overHealAbsorbGlow = CompactRaidFrame5OverHealAbsorbGlow {
 }
 newUnit = true
 hasDispelMagic = false
 hasDispelCurse = false
 selectionHighlight = CompactRaidFrame5SelectionHighlight {
 }
 myHealAbsorbLeftShadow = CompactRaidFrame5MyHealAbsorbLeftShadow {
 }
 totalAbsorbOverlay = CompactRaidFrame5TotalAbsorbOverlay {
 }
 unit = "party4"
 unitExists = true
 displayedUnit = "party4"
 unusedFunc = <function> defined @Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:46
 updateAllEvent = "GROUP_ROSTER_UPDATE"
 statusText = CompactRaidFrame5StatusText {
 }
 horizDivider = CompactRaidFrame5HorizDivider {
 }
 applyFunc = <function> defined @Interface\AddOns\Blizzard_CompactRaidFrames\Blizzard_CompactRaidFrameContainer.lua:324
 roleIcon = CompactRaidFrame5RoleIcon {
 }
 menu = <function> defined @Interface_Wrath\FrameXML\CompactUnitFrame.lua:260
 optionTable = <table> {
 }
 otherHealPrediction = CompactRaidFrame5OtherHealPrediction {
 }
 dispelDebuffFrames = <table> {
 }
 buffFrames = <table> {
 }
 maxDebuffs = 3
 centerStatusIcon = CompactRaidFrame5CenterStatusIcon {
 }
 dropDown = CompactRaidFrame5DropDown {
 }
 myHealAbsorb = CompactRaidFrame5MyHealAbsorb {
 }
 maxBuffs = 3
 vertLeftBorder = CompactRaidFrame5VertLeftBorder {
 }
 horizBottomBorder = CompactRaidFrame5HorizBottomBorder {
 }
 name = CompactRaidFrame5Name {
 }
 readyCheckIcon = CompactRaidFrame5ReadyCheckIcon {
 }
 totalAbsorb = CompactRaidFrame5TotalAbsorb {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'frames' (a nil value)"
BuffOverlay = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\BuffOverlay\Libs\AceAddon-3.0\AceAddon-3.0.lua:367
 UpdateCustomBuffs = <function> defined @Interface\AddOns\BuffOverlay\BuffOverlay.lua:81
 Enable = <function> defined @Interface\AddOns\BuffOverlay\Libs\AceAddon-3.0\AceAddon-3.0.lua:294
 RegisterChatCommand = <function> defined @Interface\AddOns\BuffOverlay\Libs\AceConsole-3.0\AceConsole-3.0.lua:85
 print = <function> defined @Interface\AddOns\BuffOverlay\BuffOverlay.lua:281
 EnableModule = <function> defined @Interface\AddOns\BuffOverlay\Libs\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\BuffOverlay\Libs\AceAddon-3.0\AceAddon-3.0.lua:210
 IterateEmbeds = <function> defined @Interface\AddOns\BuffOverlay\Libs\AceAddon-3.0\AceAddon-3.0.lua:442
 ConsolidateChildren = <function> defined @Interface\AddOns\BuffOverlay\BuffOverlay.lua:103
 UpdateChildInfo = <function> defined @Interface\AddOns\BuffOverlay\BuffOverlay.lua:92
 defaultModuleLibraries = <table> {
 }
 UnregisterChatCommand = <functio
---------------------
Message: Interface\FrameXML\ObjectAPI\Spell.lua:27: bad argument #1 to 'DoesSpellExist' (outside of expected range -2147483648 to 2147483647 - Usage: local spellExists = C_Spell.DoesSpellExist(spellID))
Time: Mon Oct  3 04:53:24 2022
Count: 1
Stack: Interface\FrameXML\ObjectAPI\Spell.lua:27: bad argument #1 to 'DoesSpellExist' (outside of expected range -2147483648 to 2147483647 - Usage: local spellExists = C_Spell.DoesSpellExist(spellID))
[string "=[C]"]: in function `DoesSpellExist'
[string "@Interface\FrameXML\ObjectAPI\Spell.lua"]:27: in function `IsSpellEmpty'
[string "@Interface\FrameXML\ObjectAPI\Spell.lua"]:52: in function `ContinueOnSpellLoad'
[string "@Interface\AddOns\BuffOverlay\Options.lua"]:19: in function <Interface\AddOns\BuffOverlay\Options.lua:7>
[string "@Interface\AddOns\BuffOverlay\Options.lua"]:65: in function `BuffOverlay_GetClasses'
[string "@Interface\AddOns\BuffOverlay\Options.lua"]:372: in function `Options'
[string "@Interface\AddOns\BuffOverlay\BuffOverlay.lua"]:140: in function <Interface\AddOns\BuffOverlay\BuffOverlay.lua:132>
[string "=[C]"]: ?
[string "@Interface\AddOns\ArenaStats\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...AddOns\ArenaStats\Libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\ArenaStats\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:498: in function `InitializeAddon'
[string "@Interface\AddOns\ArenaStats\Libs\AceAddon-3.0\AceAddon-3.0.lua"]:623: in function <...AddOns\ArenaStats\Libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

### Reproduction Steps

Every time now.

### Last Working Version

addon works on and off, hard for me to tell.

### Screenshots

![캡처](https://user-images.githubusercontent.com/58577266/193473542-0818dbff-4414-4d9e-b9db-f1bcdcc39965.PNG)

**Comment by clicketz** [comment]
v11.4.1 is quite an old version. I recommend upgrading to the latest version. As the code has changed so much (including with respect to the frames table, which all your errors are about), I can't really help much other than to tell you to upgrade.

That being said, I'll add some additional checks in the current codebase just in case.

Also just a reminder, if the reason you're hesitant to update is because you don't want to keep re-adding custom spells, spells can be added through the in-game interface now and will persist through updates.

**Comment by tickix** [comment]
Ah, I didn't realize. Thanks for the support!

**Comment by tickix** [comment]
As a sidenote, can I request a feature?

**Comment by clicketz** [comment]
> As a sidenote, can I request a feature?

Yes, of course.

**Comment by tickix** [comment]
A feature I've wanted for this addon for years is the ability to add
another rows of abilities that I could add different abilities on. Part of
the reason I was slow to update was because I would make a copy of the
addon with a different name and add another row. For example, I'd have your
version on the top right of the frame and then I'd have offensive abilities
(Bloodlust, Power Infusion, Icy Veins, etc etc) on the middle left of the
frame. My request is that there be a way to add another row/version of the
addon and I could add custom spells to each bar. For example, another addon
Big Debuffs has this feature like in the screenshot below. It's an addon
that tracks the CDs of any ability I want on a bar (when kick is coming
back up from opponent rogues, for example). I can have all interrupts (like
kick) on 1 bar and their defensives on another bar (like cloak of shadows).
I can customize how each bar looks like and what spells goes on each bar.
Attached are screenshots for your visibility.

https://gyazo.com/51eadb27f2910b284a72258609fc3ad4
https://gyazo.com/1f04cfed23854a34165f177898851828
https://gyazo.com/9e9a9bb3e586de01506079c44bf3448c

Thank you very much, I like this addon a lot.

**Comment by clicketz** [comment]
Can you do me a favor and open a new feature request here: https://github.com/clicketz/buff-overlay/issues/new/choose

You can just copy/paste all of this. It just helps me track things better internally.

As for the request, yeah, that does sound like a good idea.

**Comment by tickix** [comment]
Done, thanks!!
