### ISSUE TITLE
Fix for the AshToAsh

### ISSUE THREAD

**Issue by kurapica** [clicketz/buff-overlay#8]
### Description

Just found your addon, happy to see it provide the support to the AshToAsh, and with a special fix :).  

I thought you can simple that by change the AshToAsh setting to

```lua

    ["AshToAsh"] = {
        {
            frame = "^AshToAshUnit%d+Unit%d+",
            type = "raid",
            unit = "unit",
        },
        {
            frame = "^AshToAshPet%d+Unit%d+",
            type = "raid",
            unit = "unit",
        },
        {
            frame = "^AshToAshUnitWatch%d+Unit%d+",
            type = "raid",
            unit = "unit",
        },
    },
```

There are three panel type in ATA, so the unit frame name has three patterns.

Then you don't need to check the `AshToAshUnit%dShadowGroupHeaderUnitButton` since ATA will create unit frames dynamicly, and check the shadow group header won't be able to catch them all.

**Comment by clicketz** [comment]
The main issue is that BO obtains frames by hooking `CreateFrame` and matching any found frames to the patterns shown. ATA is using something different for its frame creation IIRC (reusing from a pool? I don't remember exactly). There's actually no active search for frames in BO, so the dynamic nature of ATA not using `CreateFrame` makes it challenging to find the frame references without searching every time the group changes.

Could you give me a bit more info in how ATA handles its frames? I'd be happy to try and get a more robust fix :)

**Comment by kurapica** [comment]
The CreateFrame can track all the unit frames generated by ATA. Since ATA can be re-layout during combat, the frames in the pool will use nil or clear as the unit, It won't keep a pre-assigned unit that'd cause more cpu to check the un-existed unit's states , and use a real unit when they are taken from the pool for a new member.

I discussed that in the topic [Solution to re-layout raid panel during combat](https://www.wowinterface.com/forums/showthread.php?p=338908).

You call `UpdateUnits` after the `GROUP_ROSTER_UPDATE`, and with 1 more call after 1 sec, that'd be the problem why you don't get the new unit. 

To re-layout during the combat, I can't do that with system event, I can only detect the unit changes by the **ShadowGroupHeader**, and the changes could be triggered dozens times in the same time, that'd cause a big performance issue if I re-layout the panel for each trigger.

So I use a macro condition state check to trigger the re-layout, reset it when any changes triggered, no matter how many times it triggered, the secure state driver would notify ATA after a tiny time, so I can do one time re-layout without performance issue. 

But the time between `GROUP_ROSTER_UPDATE` and the re-layout is uncertain, 1 second delay may not fix that.

In Scorpio, I use observable objects as data sources, the usage can be found at [03.observable.md](https://github.com/kurapica/Scorpio/blob/master/Docs/003.observable.md) If you are interested.

I have do some changes on your code, will test it when I get home.

First change the settings like 

```lua
    ["AshToAsh"] = {
        {
            frame = "^AshToAshUnit%d+Unit%d+",
            type = "raid",
            unit = "unit",
        },
        {
            frame = "^AshToAshPet%d+Unit%d+",
            type = "raid",
            unit = "unit",
        },
        {
            frame = "^AshToAshUnitWatch%d+Unit%d+",
            type = "raid",
            unit = "unit",
        },
        -- Add a fix for special addon
        fix = function(frame)
            -- Proxy UI provide more features to the raw in the Scorpio
            local proxy = Scorpio.UI.GetProxyUI(frame)

            -- UnitFrameSubject is a data source provide the unit changes on an unit frame
            -- So the unit changes will be pushed
            Scorpio.Secure.UnitFrameSubject(proxy):Subscribe(function(unit)
                if unit and unit ~= "clear" then
                    BuffOverlay:AddUnitFrame(frame, unit)
                else
                    -- should this be added?
                    BuffOverlay:RemoveUnitFrame(frame)
                end
            end)
        end
    },
```

Then the `AddOnsExist`, change
```lua
for _, frameInfo in pairs(info) do
    enabledPatterns[frameInfo.frame] = { unit = frameInfo.unit, type = frameInfo.type }
end
```

To

```lua
for _, frameInfo in pairs(info) do
    if type(frameInfo) == "table" then
        enabledPatterns[frameInfo.frame] = { unit = frameInfo.unit, type = frameInfo.type, fix = info.fix }
    end
end
```

At last, replace the cleanFrameCache to

```lua
local function cleanFrameCache()
    for frame in pairs(tempFrameCache) do
        local name = frame:GetName()

        for addOnFramePattern, data in pairs(enabledPatterns) do
            if name:match(addOnFramePattern) then
                BuffOverlay.frames[frame] = { unit = data.unit, type = data.type }
                if data.fix then data.fix(frame) end -- special fix
                break
            end
        end

        tempFrameCache[frame] = nil
    end
end
```

**Comment by kurapica** [comment]
Interesting, seems the secure hook on CreateFrame can't track the UI generated by Scorpio.  I use private environment as modules affect that. So I can only do that with the Scorpio's style system.

You can remove the fix for AshToAsh in `addonFrameInfo` and `cleanFrameCache`, just add a fix in `AddOnsExist` like 

```lua

local function AddOnsExist()
    local addonsExist = false
    for addon, info in pairs(addonFrameInfo) do
        if IsAddOnLoaded(addon) then
            for _, frameInfo in pairs(info) do
                enabledPatterns[frameInfo.frame] = { unit = frameInfo.unit, type = frameInfo.type }
            end

            if not addonsExist then
                addonsExist = true
            end

            -- Fix for ElvUI Party Pet Frames. They are not in the frame cache due
            -- to the way ElvUI creates them. This is unique to party pets, thankfully.
            if addon == "ElvUI" then
                for i = 1, 5 do
                    framesToFind["ElvUF_PartyGroup1UnitButton" .. i .. "Pet"] = "unit"
                end
            end
        end
    end

    -- Fix for AshToAsh
    if IsAddOnLoaded("AshToAsh") then
        -- Declare an ui style property to receive the unit from the unit frame
        Scorpio.UI.Property {
            name            = "BuffOverlayUnit",
            require         = Scorpio.Secure.UnitFrame,
            nilable         = true,
            set             = function(self, unit)
                print("[Unit]" .. self:GetName() .. " To " .. (unit or "clear"))

                if unit and unit ~= "clear" then
                    BuffOverlay:AddUnitFrame(Scorpio.UI.GetRawUI(self), unit)
                end
            end,
        }

        -- Add the property to the base unit frame class's default skin
        -- So all unit frame generated from Scorpio will use that
        Scorpio.UI.Style.UpdateSkin("Default", {
            [Scorpio.Secure.UnitFrame] = {
                -- Scorpio.Wow.Unit() is an observable data source
                -- provide the unit from the unit frame
                BuffOverlayUnit = Scorpio.Wow.Unit()
            }
        }, true)
    end

    addOnsExist = addonsExist
    BuffOverlay.addons = addonsExist
    return addonsExist
end
```

I test it, should works now.

**Comment by clicketz** [comment]
> Interesting, seems the secure hook on CreateFrame can't track the UI generated by Scorpio. I use private environment as modules affect that. So I can only do that with the Scorpio's style system.
>

Yeah, this is what I remember seeing when I first tested with ATA. I never did dive in to figure out why though. I'll look over your changes soon when I have some more time, but at a glance it all looks good.
