### ISSUE TITLE
Any plan for localization?

### ISSUE THREAD

**Issue by EKE00372** [clicketz/buff-overlay#9]
### Description

I recommend some friends use BuffOverlay, but some of them are not good in english.

seems no localization file yet, if plan for this, i can support zhTW/zhCN.

**Comment by clicketz** [comment]
Yes, good idea. I appreciate the translation help. I will set it up soon.

**Comment by clicketz** [comment]
I've added localization support with release v12.3. Please use [curseforge's localization interface](https://www.curseforge.com/wow/addons/buff-overlay/localization) if you'd like to contribute. Thanks!

**Comment by EKE00372** [comment]
quickly do 90% translate for both locale

can push if you feel it's ok, remainder part should be later unless i sure what it mean, where it be used,  and how to translate is better.

**Comment by clicketz** [comment]
Looks great, pushing out now.
